  
name: Flake8

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Flake8
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install Dependencies
      run: |
        pip install -r requirements/requirements_test.txt
    - name: Flake8
      run: |
        flake8 src/ --count --max-line-length=120
